[package]
name = "p2p"
version = "0.1.0"
license = "MIT"
description = "Minimal implementation for a multiplexed p2p network."
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"

[dependencies]
yamux = { path = "yamux", package = "tokio-yamux" }
secio = { path = "secio" }

futures = "0.1"
tokio = "0.1"
log = "0.4"
bytes = "0.4"

flatbuffers = "0.5.0"

[dev-dependencies]
env_logger = "0.6.0"
fnv = "1.0"
discovery = { path = "discovery" }

[workspace]
members = ["yamux", "secio", "discovery", "ping"]
